unstable_features = true

max_width = 100
#hard_tabs = true
#tab_spaces = 2

merge_derives = false
merge_imports = true

normalize_comments = true
normalize_doc_attributes = true

reorder_impl_items = true
group_imports = "StdExternalCrate"

overflow_delimited_expr = true
control_brace_style = "ClosingNextLine"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
