use libc::c_int;
use ffi::*;

bitflags! {
	flags Flags: c_int {
		const NOFILE        = AVFMT_NOFILE,
		const NEEDNUMBER    = AVFMT_NEEDNUMBER,
		const SHOW_IDS      = AVFMT_SHOW_IDS,
		const RAWPICTURE    = AVFMT_RAWPICTURE,
		const GLOBALHEADER  = AVFMT_GLOBALHEADER,
		const NOTIMESTAMPS  = AVFMT_NOTIMESTAMPS,
		const GENERIC_INDEX = AVFMT_GENERIC_INDEX,
		const TS_DISCONT    = AVFMT_TS_DISCONT,
		const VARIABLE_FPS  = AVFMT_VARIABLE_FPS,
		const NODIMENSIONS  = AVFMT_NODIMENSIONS,
		const NOSTREAMS     = AVFMT_NOSTREAMS,
		const NOBINSEARCH   = AVFMT_NOBINSEARCH,
		const NOGENSEARCH   = AVFMT_NOGENSEARCH,
		const NO_BYTE_SEEK  = AVFMT_NO_BYTE_SEEK,
		const ALLOW_FLUSH   = AVFMT_ALLOW_FLUSH,
		const TS_NONSTRICT  = AVFMT_TS_NONSTRICT,
		const TS_NEGATIVE   = AVFMT_TS_NEGATIVE,
		const SEEK_TO_PTS   = AVFMT_SEEK_TO_PTS,
	}
}

