name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install ffmpeg
      run: sudo apt-get -y install ffmpeg pkg-config libavutil-dev libavformat-dev libavfilter-dev libavdevice-dev
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --all --verbose --features=ffmpeg_4_4
